-- ==========================================
-- BB24 Supabase Database Seeding Script
-- Run this script in the Supabase SQL Editor
-- ==========================================

DO $$
DECLARE
    founder_id UUID := '81194f5b-9b4e-4f35-950f-2c07fb8d7a00';
    org_id UUID;
    c1_id UUID := '81194f5b-9b4e-4f35-950f-2c07fb8d7a01';
    c2_id UUID := '81194f5b-9b4e-4f35-950f-2c07fb8d7a02';
    c3_id UUID := '81194f5b-9b4e-4f35-950f-2c07fb8d7a03';
    c4_id UUID := '81194f5b-9b4e-4f35-950f-2c07fb8d7a04';
    c5_id UUID := '81194f5b-9b4e-4f35-950f-2c07fb8d7a05';
    c6_id UUID := '81194f5b-9b4e-4f35-950f-2c07fb8d7a06';
    c7_id UUID := '81194f5b-9b4e-4f35-950f-2c07fb8d7a07';
    c8_id UUID := '81194f5b-9b4e-4f35-950f-2c07fb8d7a08';
    p1_id UUID := '91194f5b-9b4e-4f35-950f-2c07fb8d7a01';
    p2_id UUID := '91194f5b-9b4e-4f35-950f-2c07fb8d7a02';
    p3_id UUID := '91194f5b-9b4e-4f35-950f-2c07fb8d7a03';
BEGIN
    -- 0. Clean up any existing seed user to ensure clean schema states and avoid 500 error
    DELETE FROM auth.users WHERE email = 'ceo.bb24.agency@gmail.com';

    -- 1. Create the user in auth.users
    INSERT INTO auth.users (
        id,
        email,
        encrypted_password,
        email_confirmed_at,
        confirmed_at,
        raw_app_meta_data,
        raw_user_meta_data,
        aud,
        role
    ) VALUES (
        founder_id,
        'ceo.bb24.agency@gmail.com',
        crypt('agencyceo123', gen_salt('bf')),
        now(),
        now(),
        '{"provider": "email", "providers": ["email"]}',
        '{"first_name": "Dev", "last_name": "Founder"}',
        'authenticated',
        'authenticated'
    );

    -- 2. Retrieve the organization_id generated by the trigger
    SELECT organization_id INTO org_id FROM public.profiles WHERE id = founder_id;

    -- 3. If organization_id was found, proceed with insertion
    IF org_id IS NOT NULL THEN
        -- Seed Clients
        INSERT INTO public.clients (id, organization_id, company_name, contact_person, email, phone, monthly_fee, contract_start_date, contract_end_date, status)
        VALUES
            (c1_id, org_id, 'GS Ayurveda', 'GS Ayurveda Team', 'gsayurveda@email.com', '+91 98765 00001', 15000, '2026-01-01', '2026-12-31', 'active'),
            (c2_id, org_id, 'Ashvastra Creation', 'Ashvastra Team', 'ashvastra@email.com', '+91 98765 00002', 28000, '2026-03-01', '2026-12-31', 'active'),
            (c3_id, org_id, 'The Webbia & Ikie Posting', 'Webbia Team', 'thewebbia@email.com', '+91 98765 00003', 6000, '2026-04-01', '2026-12-31', 'active'),
            (c4_id, org_id, 'Chillqubig', 'Chillqubig Team', 'chillqubig@email.com', '+91 98765 00004', 5000, '2026-04-01', '2026-12-31', 'active'),
            (c5_id, org_id, 'OncoAdvisor', 'OncoAdvisor Team', 'oncoadvisor@email.com', '+91 98765 00005', 10000, '2026-05-01', '2026-12-31', 'active'),
            (c6_id, org_id, 'The Webbia Website', 'Webbia Website Team', 'thewebbia.web@email.com', '+91 98765 00006', 13000, '2026-04-01', '2026-07-31', 'active'),
            (c7_id, org_id, 'WellaVitta', 'WellaVitta Team', 'wellavitta@email.com', '+91 98765 00007', 8000, '2026-05-01', '2026-08-31', 'active'),
            (c8_id, org_id, 'SP Events', 'SP Events Team', 'spevents@email.com', '+91 98765 00008', 5000, '2026-03-01', '2026-03-31', 'inactive')
        ON CONFLICT (id) DO UPDATE SET
            organization_id = EXCLUDED.organization_id,
            company_name = EXCLUDED.company_name,
            contact_person = EXCLUDED.contact_person,
            email = EXCLUDED.email,
            phone = EXCLUDED.phone,
            monthly_fee = EXCLUDED.monthly_fee,
            status = EXCLUDED.status;

        -- Seed Leads
        INSERT INTO public.leads (organization_id, client_name, company_name, email, stage, source, revenue_potential)
        VALUES
            (org_id, 'Neha', 'Beauty Brand', 'neha@beautybrand.com', 'won', 'Referral', 120000),
            (org_id, 'Rohit', 'Travel Co.', 'rohit@travelco.com', 'won', 'LinkedIn Outbound', 95000),
            (org_id, 'Rahul', 'Fintech Solutions', 'rahul@fintechsolutions.com', 'lost', 'Cold Outreach', 180000),
            (org_id, 'Rajesh', 'E-Commerce Hub', 'rajesh@ecommercehub.com', 'negotiation', 'Google Ads', 250000),
            (org_id, 'Priya', 'Fashion Studio', 'priya@fashionstudio.com', 'negotiation', 'Instagram', 85000),
            (org_id, 'Dr. Batra', 'Health Clinic', 'drbatra@healthclinic.com', 'proposal_sent', 'Referral', 150000),
            (org_id, 'Vikram', 'FitLife Gym', 'vikram@fitlife.com', 'proposal_sent', 'Cold Outreach', 75000),
            (org_id, 'Amit', 'Realty Pro', 'amit@realtypro.com', 'contacted', 'Referral', 350000),
            (org_id, 'Pooja', 'EduLearn', 'pooja@edulearn.com', 'new_lead', 'Organic Search', 60000),
            (org_id, 'Karan', 'TechStartup', 'karan@techstartup.com', 'new_lead', 'LinkedIn Outbound', 200000),
            (org_id, 'Sneha', 'Food Delight', 'sneha@fooddelight.com', 'new_lead', 'Google Ads', 45000),
            (org_id, 'Sanjay', 'AutoDrive Motors', 'sanjay@autodrive.com', 'contacted', 'Cold Outreach', 280000)
        ON CONFLICT DO NOTHING;

        -- Seed Projects
        INSERT INTO public.projects (id, organization_id, client_id, name, description, start_date, due_date, status)
        VALUES
            (p1_id, org_id, c1_id, 'Social Media & Content Marketing', 'Monthly social media management, content creation, and organic growth strategy for Ayurveda brand.', '2026-01-01', '2026-12-31', 'active'),
            (p2_id, org_id, c2_id, 'Brand Identity & Digital Marketing', 'Full-scale brand identity development, digital marketing, and paid ad campaigns.', '2026-03-01', '2026-12-31', 'active'),
            (p3_id, org_id, c6_id, 'Website Development', 'Full website design and development project on a one-time basis.', '2026-04-01', '2026-07-31', 'active')
        ON CONFLICT (id) DO UPDATE SET
            organization_id = EXCLUDED.organization_id,
            client_id = EXCLUDED.client_id,
            name = EXCLUDED.name,
            description = EXCLUDED.description,
            status = EXCLUDED.status;

        -- Seed Invoices
        INSERT INTO public.invoices (organization_id, client_id, invoice_number, amount, due_date, status, paid_at)
        VALUES
            (org_id, c1_id, 'INV-2026-006', 15000, '2026-06-15', 'unpaid', null),
            (org_id, c1_id, 'INV-2026-005', 7500, '2026-05-15', 'paid', '2026-05-10T00:00:00Z'::timestamp),
            (org_id, c2_id, 'INV-2026-004', 28000, '2026-06-10', 'overdue', null),
            (org_id, c6_id, 'INV-2026-003', 13000, '2026-04-30', 'paid', '2026-04-28T00:00:00Z'::timestamp),
            (org_id, c8_id, 'INV-2026-001', 5000, '2026-03-20', 'paid', '2026-03-18T00:00:00Z'::timestamp)
        ON CONFLICT DO NOTHING;
        
        RAISE NOTICE 'Seed completed successfully!';
    ELSE
        RAISE EXCEPTION 'Failed to locate organization_id for user %', founder_id;
    END IF;
END $$;
